# Generated by Django 2.2.7 on 2020-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200125_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('Id_No', 'company')},
        ),
    ]
