# Generated by Django 2.2.7 on 2020-01-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200127_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Id_No',
            new_name='adhaar',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='adhar',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='testapp.Country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('number', 'company')},
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.State'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
    ]
